### PR TITLE
Update LICENSE

### LINKED ISSUE #14: Missing LICENSE

### PR DESCRIPTION
**Pull request by szarroug3**
Fixes #14
Update to #15

### CODE REVIEW

**Comment by WOLFI3654** [comment]
Still got one Problem :.:
I don't want my Project to be used in any Commercial way. It should not be selled by third persons :/

**Comment by szarroug3** [comment]
Hm, I'm not sure any of the free licenses grants you that. I've looked through all of them.

**Comment by WOLFI3654** [comment]
@szarroug3 Oh okay. Then its fine... 😅

**Comment by szarroug3** [comment]
Sorry about that.

**Comment by WOLFI3654** [comment]
@szarroug3 Not your fault 😅

**Pull request merged**
