### PR TITLE
Create LICENSE

### LINKED ISSUE #14: Missing LICENSE

### PR DESCRIPTION
**Pull request by szarroug3**
Fixes #14

### CODE REVIEW

**Comment by WOLFI3654** [comment]
Not aming for a MIT license. This should not be selled in any way. And nobody should have the rights to publish it without my noitice/ refeering to me in a direct way

**Comment by szarroug3** [comment]
Hm, okay. I think MIT is the most standard which is why I picked it. I think if we added your name to the license, they'd have to refer to you directly.

The license says:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So if we add you, they'd have to put your name in the license. Not having a license will not stop people from using this without mentioning you.

**Comment by szarroug3** [comment]
If you wanted another license, I can change it too.

**Comment by WOLFI3654** [comment]
hm okay. Looks right

**Comment by WOLFI3654** [comment]
Add name and its fine

**Comment by szarroug3** [comment]
looks like you merged before the name add.. i'll put in another PR

**Comment by WOLFI3654** [comment]
@szarroug3 Whops sorry

**Pull request merged**
